- name: playbook for mongodb
  become: yes
  hosts: mongodb
  ignore_errors: yes
  tasks:
  - name: copy mongodb yum repo file
    ansible.builtin.copy:
      src: /home/centos/14th-Feb-Ansible-Roboshop/mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mondb-org package
    ansible.builtin.package:
      name: mongodb-org
      state: present
  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1 '
      replace: '0.0.0.0'
  - name: start and enable mondb-org
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes