- name: playbook for shipping
  become: yes
  hosts: catalogue
  ignore_errors: yes
  tasks:
  ansible.builtin.package:
    name: maven
    state: present
- name: create user
  ansible.builtin.user:
    name: roboshop
    state: present
- name: create directory for application
  ansible.builtin.file:
    name: /app
    state: directory
- name: download application code
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
    dest: /tmp
- name: unzip application code
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes
- name: install dependencies
  ansible.builtin.shell: "mvn clean package"
  args:
    chdir: /app
- name: move jar file and rename
  ansible.builtin.copy:
    src: /app/target/shipping-1.0.jar
    dest: /app/shipping.jar
    remote_src: yes
- name: copy shipping service file
  ansible.builtin.copy:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service
- name: deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: install mongodb client package
  ansible.builtin.package:
    name: mysql
    state: present
- name: load schema
  ansible.builtin.shell: 'mysql -h mysql.kiranku.online -uroot -pRoboShop@1 < /app/schema/shipping.sql'
- name: start and enable catalogue service
  ansible.builtin.service:
    name: shipping
    state: started
    enabled: yes